### ISSUE TITLE
Wondering about production "readyness"

### ISSUE THREAD

**Issue by cavi21** [PRX/announce#10]
Hi there! I was looking to implement also PubSub pattern based on **shoryuken** and find this gem, that looks similar of what I had in mind. And so I was wondering if you are using this on production? or if it's maintain? no worries if not

Thanks! have a nice friday

**Comment by kookster** [comment]
Hello, we use it in production to communicate between about 5 different apps now, most of which are also in our github repo.

**Comment by cavi21** [comment]
Thanks @kookster nice to hear it! I'll give it a shot then! and if there is anything I can help with I'll we submit a PR, if you are ok with that.

**Comment by kookster** [comment]
Happy to accept PRs, and to offer info/answer questions as you try to use `announce`.
