### ISSUE TITLE
Any specific permission on the AWS SNS and SQS policy for the user?

### ISSUE THREAD

**Issue by agustin** [PRX/announce#12]
Hi @kookster sorry to bother with this stuff, but is there any specific permission that the AWS user should have to handle the SNS and SQS? In Shoryuken's Wiki there is a [Amazon SQS IAM Policy for Shoryuken](https://github.com/phstc/shoryuken/wiki/Amazon-SQS-IAM-Policy-for-Shoryuken) do you have something like that but for SNS?

Thanks! Cheers

**Comment by kookster** [comment]
I think the shoryuken adapter has a method to create a policy?
- Andrew

**Comment by agustin** [comment]
Will look into that! Thanks!
